ci: github actions missing remotes dependency
https://github.com/inrae/airGRiwrm/actions/runs/10121471265/job/27992451097
> remotes::install_gitlab("in-wop/seinebasin", host = "gitlab.irstea.fr")
Error: Error in loadNamespace(x) : there is no package called ‘remotes’

Refs #162